feat(24.10): forward-port 24.04 slices (#339)
This commit imports all slices from the 24.04 release.

libnode109 is not available for Ubuntu 24.10. nodejs depends on
libnode115.

The tests/ dir and spread.yaml files were imported. Later on, the
tests/spread/integration/systemd/ dir was removed due to earlier issues
with systemd slices.

The 24.04 slices of systemd are raising too much conflicts with the
24.10 package. We need an expert doing the backport here, if systemd is
needed in 24.10. TODO seek help from Philip @Meulengracht.

Error logs below (long):

    INFO: Installing systemd-dev_copyright on amd64...
    INFO: Installing systemd-dev_dbus-interfaces on amd64...
    INFO: Installing systemd_bins on amd64...
    ...
    error: cannot extract from package "systemd": no content at:
    - /usr/bin/systemd
    - /usr/bin/systemd-cryptenroll
    - /usr/bin/systemd-cryptsetup
    - /usr/bin/systemd-repart
    - /usr/lib/*-linux-*/cryptsetup/libcryptsetup-token-systemd-fido2.so
    - /usr/lib/*-linux-*/cryptsetup/libcryptsetup-token-systemd-pkcs11.so
    - /usr/lib/*-linux-*/cryptsetup/libcryptsetup-token-systemd-tpm2.so
    - /usr/lib/systemd/repart/definitions/confext.repart.d/10-root.conf
    - /usr/lib/systemd/repart/definitions/confext.repart.d/20-root-verity.conf
    - /usr/lib/systemd/repart/definitions/confext.repart.d/30-root-verity-sig.conf
    - /usr/lib/systemd/repart/definitions/portable.repart.d/10-root.conf
    - /usr/lib/systemd/repart/definitions/portable.repart.d/20-root-verity.conf
    - /usr/lib/systemd/repart/definitions/portable.repart.d/30-root-verity-sig.conf
    - /usr/lib/systemd/repart/definitions/sysext.repart.d/10-root.conf
    - /usr/lib/systemd/repart/definitions/sysext.repart.d/20-root-verity.conf
    - /usr/lib/systemd/repart/definitions/sysext.repart.d/30-root-verity-sig.conf
    - /usr/lib/systemd/system-generators/systemd-cryptsetup-generator
    - /usr/lib/systemd/system-generators/systemd-integritysetup-generator
    - /usr/lib/systemd/system-generators/systemd-veritysetup-generator
    - /usr/lib/systemd/system/cryptsetup-pre.target
    - /usr/lib/systemd/system/cryptsetup.target
    - /usr/lib/systemd/system/initrd-root-device.target.wants/remote-cryptsetup.target
    - /usr/lib/systemd/system/initrd-root-device.target.wants/remote-veritysetup.target
    - /usr/lib/systemd/system/initrd-root-fs.target.wants/systemd-repart.service
    - /usr/lib/systemd/system/integritysetup-pre.target
    - /usr/lib/systemd/system/integritysetup.target
    - /usr/lib/systemd/system/quotaon.service
    - /usr/lib/systemd/system/remote-cryptsetup.target
    - /usr/lib/systemd/system/remote-veritysetup.target
    - /usr/lib/systemd/system/sysinit.target.wants/cryptsetup.target
    - /usr/lib/systemd/system/sysinit.target.wants/integritysetup.target
    - /usr/lib/systemd/system/sysinit.target.wants/systemd-repart.service
    - /usr/lib/systemd/system/sysinit.target.wants/veritysetup.target
    - /usr/lib/systemd/system/system-systemd\x2dcryptsetup.slice
    - /usr/lib/systemd/system/system-systemd\x2dveritysetup.slice
    - /usr/lib/systemd/system/systemd-quotacheck.service
    - /usr/lib/systemd/system/systemd-repart.service
    - /usr/lib/systemd/system/systemd-sysupdate-reboot.service
    - /usr/lib/systemd/system/systemd-sysupdate-reboot.timer
    - /usr/lib/systemd/system/systemd-sysupdate.service
    - /usr/lib/systemd/system/systemd-sysupdate.timer
    - /usr/lib/systemd/system/systemd-time-wait-sync.service
    - /usr/lib/systemd/system/veritysetup-pre.target
    - /usr/lib/systemd/system/veritysetup.target
    - /usr/lib/systemd/systemd-cryptsetup
    - /usr/lib/systemd/systemd-integritysetup
    - /usr/lib/systemd/systemd-sysupdate
    - /usr/lib/systemd/systemd-time-wait-sync
    - /usr/lib/systemd/systemd-veritysetup
    INFO: Installing systemd_catalog on amd64...
    INFO: Installing systemd_config on amd64...
    INFO: Installing systemd_copyright on amd64...
    INFO: Installing systemd_dbus-services on amd64...
    INFO: Installing systemd_extras on amd64...
    ...
    error: cannot extract from package "systemd": no content at:
    - /etc/sysctl.d/99-sysctl.conf
    - /usr/share/systemd/tmp.mount
    INFO: Installing systemd_generated-services on amd64...
    INFO: Installing systemd_kernel-install on amd64...
    INFO: Installing systemd_kernel-parameters on amd64...
    INFO: Installing systemd_libs on amd64...
    ...
    error: cannot extract from package "systemd": no content at:
    - /usr/lib/*-linux-*/cryptsetup/libcryptsetup-token-systemd-fido2.so
    - /usr/lib/*-linux-*/cryptsetup/libcryptsetup-token-systemd-pkcs11.so
    - /usr/lib/*-linux-*/cryptsetup/libcryptsetup-token-systemd-tpm2.so
    INFO: Installing systemd_modprobe-config on amd64...
    INFO: Installing systemd_network on amd64...
    INFO: Installing systemd_pam-profile on amd64...
    INFO: Installing systemd_pcrlock on amd64...
    INFO: Installing systemd_polkit on amd64...
    INFO: Installing systemd_repart on amd64...
    ...
    error: cannot extract from package "systemd": no content at:
    - /usr/lib/systemd/repart/definitions/confext.repart.d/10-root.conf
    - /usr/lib/systemd/repart/definitions/confext.repart.d/20-root-verity.conf
    - /usr/lib/systemd/repart/definitions/confext.repart.d/30-root-verity-sig.conf
    - /usr/lib/systemd/repart/definitions/portable.repart.d/10-root.conf
    - /usr/lib/systemd/repart/definitions/portable.repart.d/20-root-verity.conf
    - /usr/lib/systemd/repart/definitions/portable.repart.d/30-root-verity-sig.conf
    - /usr/lib/systemd/repart/definitions/sysext.repart.d/10-root.conf
    - /usr/lib/systemd/repart/definitions/sysext.repart.d/20-root-verity.conf
    - /usr/lib/systemd/repart/definitions/sysext.repart.d/30-root-verity-sig.conf
    - /usr/lib/systemd/system/initrd-root-fs.target.wants/systemd-repart.service
    - /usr/lib/systemd/system/sysinit.target.wants/systemd-repart.service
    - /usr/lib/systemd/system/systemd-repart.service
    INFO: Installing systemd_system-generators on amd64...
    ...
    error: cannot extract from package "systemd": no content at:
    - /usr/lib/systemd/system-generators/systemd-cryptsetup-generator
    - /usr/lib/systemd/system-generators/systemd-integritysetup-generator
    - /usr/lib/systemd/system-generators/systemd-veritysetup-generator
    INFO: Installing systemd_system-services on amd64...
    ...
    error: cannot extract from package "systemd": no content at:
    - /usr/lib/systemd/system/cryptsetup-pre.target
    - /usr/lib/systemd/system/cryptsetup.target
    - /usr/lib/systemd/system/initrd-root-device.target.wants/remote-cryptsetup.target
    - /usr/lib/systemd/system/initrd-root-device.target.wants/remote-veritysetup.target
    - /usr/lib/systemd/system/integritysetup-pre.target
    - /usr/lib/systemd/system/integritysetup.target
    - /usr/lib/systemd/system/quotaon.service
    - /usr/lib/systemd/system/remote-cryptsetup.target
    - /usr/lib/systemd/system/remote-veritysetup.target
    - /usr/lib/systemd/system/sysinit.target.wants/cryptsetup.target
    - /usr/lib/systemd/system/sysinit.target.wants/integritysetup.target
    - /usr/lib/systemd/system/sysinit.target.wants/veritysetup.target
    - /usr/lib/systemd/system/system-systemd\x2dcryptsetup.slice
    - /usr/lib/systemd/system/system-systemd\x2dveritysetup.slice
    - /usr/lib/systemd/system/systemd-quotacheck.service
    - /usr/lib/systemd/system/systemd-sysupdate-reboot.service
    - /usr/lib/systemd/system/systemd-sysupdate-reboot.timer
    - /usr/lib/systemd/system/systemd-sysupdate.service
    - /usr/lib/systemd/system/systemd-sysupdate.timer
    - /usr/lib/systemd/system/systemd-time-wait-sync.service
    - /usr/lib/systemd/system/veritysetup-pre.target
    - /usr/lib/systemd/system/veritysetup.target
    INFO: Installing systemd_sysusers-config on amd64...
    INFO: Installing systemd_tmpfiles-config on amd64...
    INFO: Installing systemd_udev-rules on amd64...
    INFO: Installing systemd_user-services on amd64...
    INFO: Installing sysvinit-utils_bins on amd64...
    INFO: Installing sysvinit-utils_config on amd64...
    INFO: Installing sysvinit-utils_copyright on amd64...