ci: re-trigger integration tests
Integration tests seem to fail due to an infra failure:
> 2025/09/17 14:24:07 Fetching index for ubuntu 24.04 noble-security main component...
> error: cannot fetch from archive: expected digest 06e550cecb576802fb8716817b5b4d6fc31512091f72c8d59cf21c160af7c43b, got ba33a67c5723de62d7b0d63d9f2083bdbdc9f07fced82a7d327d38fabe8566e2