Add .NET 8 SDK chisel slice definitions for Ubuntu 24.04 (#563)
* test: add spread tests for existing .NET 8 slices

Add integration spread tests for existing .NET 8 chisle slices.
Cherry picked from ubuntu-25.04 branch.

Signed-off-by: Dominik Viererbe <dominik.viererbe@canonical.com>

* feat: add .NET SDK slices

Add chisel slice definitions for the .NET 8 & 9 SDK.

Signed-off-by: Dominik Viererbe <dominik.viererbe@canonical.com>

* test: add spread tests for .NET SDK slices

Add integration spread tests for the .NET SDK chisle slices
introduced by the previous commit.

Signed-off-by: Dominik Viererbe <dominik.viererbe@canonical.com>

* fix: CI warnings

Removed tests/spread/integration/dotnet-sdk-9.0. This was an oversight
from we when cherry picking. .NET 9 is not in the Ubuntu archive.

> error:    slices/dotnet-sdk-8.0.yaml: libs: "contents" entries are not sorted
Sorted the entries.

Signed-off-by: Dominik Viererbe <dominik.viererbe@canonical.com>

* fix: "contents" entries are not sorted

> error: slices/dotnet-sdk-8.0.yaml: libs: "contents" entries are not sorted

Signed-off-by: Dominik Viererbe <dominik.viererbe@canonical.com>

* feat: apply PR review feedback

* add dependencies to dotnet-apphost-pack-8.0 libs slice
* add comment why dotnet-apphost-pack-8.0 should not be further sliced
* add dependencies to dotnet-sdk-8.0.yaml libs slice
* add dotnet-host-8.0_bins depenendency to dotnet-templates-8.0 libs slice
* generelize content paths of netstandard-targeting-pack-2.1-8.0 libs slice
* check smoke test output for "Hello World" text
* add new line at end of file

Co-authored-by: James Yang <zhijie.yang@canonical.com>

* fix: remove libicu from dotnet runtime dependencies

The .NET runtime does not strictly need libicu. Users can set the
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true environment variable to
run the runtime in invariant mode. This comes with restricted
functionality, but is beneficily to reduce the installation size
if the globalization data is not needed.

See also: https://learn.microsoft.com/en-us/dotnet/core/runtime-config/globalization

Signed-off-by: Dominik Viererbe <dominik.viererbe@canonical.com>

* fix: use apt-get instead of apt in scripts

Co-authored-by: Vladimir Petko <vladimir.petko@canonical.com>

* fix(dotnet): tests fail due to missing libicu

Set DOTNET_SYSTEM_GLOBALIZATION_INVARIANT environment variable
to set .NET runtime into invariant mode.

Signed-off-by: Dominik Viererbe <dominik.viererbe@canonical.com>

* fix: dotnet-runtime-8.0 test failure

The spread test for dotnet-runtime-8.0 failed due
to an accidentally introduced typo.

* refactor: split dotnet spread tests in environment, prepare, execute

Splitting the .NET related tests into the environment,
prepare, execute sections, supported by the task.yaml
syntax.

Signed-off-by: Dominik Viererbe <dominik.viererbe@canonical.com>

* fix: typo

* chore: improve libicu comment

> The core of my proposal is to let people know that it's
> a choice between including libicu and setting that environment
> variable, and I'd like to lead people towards relevant documentation
> without them having to search for it themselves.
https://github.com/canonical/chisel-releases/pull/563#discussion_r2341606516

Co-authored-by: Alex Lowe <alex.lowe@canonical.com>

* tests(.NET): add w/ and w/o libicu variants

Add variants for the dotnet spread tests with and without libicu
installed.

When libicu is not installed the environment variable
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT is set to true.

Signed-off-by: Dominik Viererbe <dominik.viererbe@canonical.com>

* feat: create dotnet-runtime-8.0_minimal slice

Creates a dotnet-runtime-8.0_minimal slice without libicu and the
dotnet-runtime-8.0_libs slice contains dotnet-runtime-8.0_minimal
and libicu.

Based on feedback from alesancor1:
> Imho the slices should cover the same functionality as the package,
> so [the dotnet-runtime-8.0_libs slice] should be included to support
> globalization.
>
> I'm not a dotnet expert, but If you want to further split the slices
> you can consider a `core` or `minimal` slices that don't include this
> kind of feature(s), and leave them for `standard` and/or `dev` slices.

Signed-off-by: Dominik Viererbe <dominik.viererbe@canonical.com>

* feat: create aspnetcore-runtime-8.0_minimal slice

Creates a aspnetcore-runtime-8.0_minimal slice without libicu and the
aspnetcore-runtime-8.0_libs slice contains
aspnetcore-runtime-8.0_minimal and libicu.

Feature pairity to dotnet-runtime-8.0_minimal, introduced with the
previous commit.

Signed-off-by: Dominik Viererbe <dominik.viererbe@canonical.com>

* feat: create dotnet-sdk-8.0_minimal slice

Creates a dotnet-sdk-8.0_minimal slice without libicu and the
dotnet-sdk-8.0_libs slice contains
dotnet-sdk-8.0_minimal and libicu.

Feature pairity to dotnet-runtime-8.0_minimal, introduced with the
previous commit.

Signed-off-by: Dominik Viererbe <dominik.viererbe@canonical.com>

* fix: trailing whitespace for dotnet-runtime-8.0 slice

> slices/dotnet-runtime-8.0.yaml
>   Error: 24:1 [trailing-spaces] trailing spaces
>   Error: 29:1 [trailing-spaces] trailing spaces

* ci: re-trigger integration tests

Integration tests seem to fail due to an infra failure:
> 2025/09/17 14:24:07 Fetching index for ubuntu 24.04 noble-security main component...
> error: cannot fetch from archive: expected digest 06e550cecb576802fb8716817b5b4d6fc31512091f72c8d59cf21c160af7c43b, got ba33a67c5723de62d7b0d63d9f2083bdbdc9f07fced82a7d327d38fabe8566e2

* feat: split .NET runtime/sdk packages into core,standard,dev slices

As suggested by Alex Santisteban:
> Different concepts are mixing here. When you group by function
> (core, minimal, dev, etc.) you need to keep that convention consistent
> across the SDF. Read this [section of chisel docs](https://documentation.ubuntu.com/chisel/en/latest/how-to/slice-a-package/#design-the-slices),
> it should be helpful to clarify things a bit.

Signed-off-by: Dominik Viererbe <dominik.viererbe@canonical.com>

* fix: chisel path conflic between with dbg packages

This commit removes the dotnet-sdk-dbg-8.0,
aspnetcore-runtime-dbg-8.0, dotnet-runtime-dbg-8.0 slice
definition files as well as the dotnet-sdk-8.0_dev,
aspnetcore-runtime-8.0_dev, dotnet-runtime-8.0_dev slice
definitions, because it is hard to create maintainable
slice definition files.

The dbg packages contain *.pdb symbol files which are
located right next to the files they provide symbols for.
This makes it impossible to use glob patterns, because
chisel can not staticly (without downloading the packages
file contents) check for file conflicts.

I may revisit the idea of creating slices for the dbg
packages in the future.

Signed-off-by: Dominik Viererbe <dominik.viererbe@canonical.com>

* fix: slice regression by re-introducing .NET libs slices

This commit re-introduces the dotnet-runtime-8.0_libs and
aspnetcore-runtime-8.0_libs slices for backwards compatibility.

This commit should be reverted in newer releases.

Co-authored-by: James Yang <zhijie.yang@canonical.com>
Signed-off-by: Dominik Viererbe <dominik.viererbe@canonical.com>

* fix(linter): trailing whitespace

Fixes the following linter errors:

> slices/aspnetcore-runtime-8.0.yaml
>   Error: 26:8 [trailing-spaces] trailing spaces
>   Error: 27:15 [trailing-spaces] trailing spaces
>   Error: 28:40 [trailing-spaces] trailing spaces
>
> slices/dotnet-runtime-8.0.yaml
>   Error: 32:8 [trailing-spaces] trailing spaces
>   Error: 33:15 [trailing-spaces] trailing spaces
>   Error: 34:36 [trailing-spaces] trailing spaces

Signed-off-by: Dominik Viererbe <dominik.viererbe@canonical.com>

---------

Signed-off-by: Dominik Viererbe <dominik.viererbe@canonical.com>
Co-authored-by: James Yang <zhijie.yang@canonical.com>
Co-authored-by: Vladimir Petko <vladimir.petko@canonical.com>
Co-authored-by: Alex Lowe <alex.lowe@canonical.com>