fix: CI warnings
> MissingCopyright: dotnet-sdk-aot-9.0 has a copyright file but it wasn't installed with: dotnet-sdk-aot-9.0_libs
This was due to dotnet-sdk-aot-9.0 incorectly using dotnet-templates_copyright.

> error: slice package "dotnet-sdk-aot-9.0" missing from archive
On ppc64el and s390x this package is not available. I droped the
recommended depenency for now, because there is no way (I am aware of)
to only add the slice on amd64 and arm64.

> error:    slices/dotnet-sdk-8.0.yaml: libs: "contents" entries are not sorted
> error:    slices/dotnet-sdk-9.0.yaml: libs: "essential" entries are not sorted
> error:    slices/dotnet-sdk-9.0.yaml: libs: "contents" entries are not sorted
Sorted the entries.

Signed-off-by: Dominik Viererbe <dominik.viererbe@canonical.com>